# url: https://y7kim.github.io
baseurl: /HelianIT

# Site settings
title: HelianIT
email: enquiries@helianit.co.uk
description: "HelianIT are experts in programme and project management. Get in touch today with your project requirements."


# Team names, titles and social links
people:
- name: Ian Powell
  pic: 1
  position: Lead Consultant
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/ian-powell-mba-ba-hons-5949801/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/ian-powell-mba-ba-hons-5949801/


# Postal address (add as many lines as necessary)
address:
  - line:
  - line:

# Build settings
markdown: kramdown
permalink: pretty
